### PR TITLE
Retry when the 503 Service Unavailable

### PR DESCRIPTION
**Pull request by manabusakai**
@jugend, thank you for an awesome gem! I like this.

I think. When the API was `503 Service Unavailable` error, it should be retried.
This idea is also written in the document.

> 5XX errors are transient errors reflecting an error internal to Amazon. A 503 error means that you are submitting requests too quickly and your requests are being throttled. If this is the case, you need to slow your request rate to one request per second.

See: https://aws.amazon.com/items/1057

I tried to fix. How is it?

```ruby
def self.send_request(opts)
  # snip...

  retry_count = 0
  begin
    res = Net::HTTP.get_response(URI::parse(request_url))
    retry_count += 1

    if res.kind_of? Net::HTTPServiceUnavailable
      raise Amazon::RequestTemporaryError, "HTTP Response: #{res.code} #{res.message}"
    elsif !res.kind_of? Net::HTTPSuccess
      raise Amazon::RequestError, "HTTP Response: #{res.code} #{res.message}"
    end

  # Retry when the 503 Service Unavailable
  rescue Amazon::RequestTemporaryError => error
    if retry_count <= MAX_RETRY_COUNT
      sleep retry_count
      retry
    else
      raise Amazon::RequestError, error
    end
  end

  Response.new(res.body)
end
```

### CODE REVIEW

**Comment by manabusakai** [comment]
This is a test method to cause the error.

```
# cat /etc/hosts
(snip...)
127.0.0.1    webservices.amazon.co.jp

# while true; do echo "HTTP/1.0 503 Service Unavailable" | nc -l 80; done
or
# while true; do echo "HTTP/1.0 500 Internal Server Error" | nc -l 80; done
```

Run the application, API request is failed.

**Comment by manabusakai** [comment]
ping @jugend

Let me know if you need any help.

**Comment by jugend** [comment]
@manabusakai Thanks for the patch.

But I think `amazon-ecs` should be just a thin wrapper for the API, implementation approach may differ for different users. By enforcing it in the API, we are kind of locking down the approach, for example, some may cache response, and load from the cache, some may prefer different intervals, and on web server, some may prefer to throttle with the help of session object etc.

Appreciate the pull, thanks.

**Comment by manabusakai** [comment]
Thank you for the reply!

> But I think amazon-ecs should be just a thin wrapper for the API, implementation approach to handle the throttle may differ for different users.

I understood the your idea.
Thanks:smile:

**Pull request closed without merging**
