### PR TITLE
Associate tags

### PR DESCRIPTION
**Pull request by salza80**
From Amazon:

Associate IDs

To be an Associate, you must sign up in each locale in which you intend to do business. That means, for example, if you have an Associate ID for the US locale, you will not get credit if you submit a PurchaseURL in the DE locale. To get credit, you must get an Associate ID in the DE locale. For more information, see Becoming an Associate.

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/AssociateIDs.html

Allow the ability to configure associate_tags for each local to receive credit when using multipe countrys.

### CODE REVIEW

**Comment by jugend** [comment]
@salza80 From a library API perspective, I think it should not handle the logic to handle the storage of the associate tags. Instead, they should be stored in your application configs.  Then overridden on each request if needed to, e.g.

Amazon::ECS.item_search('keyword', :associate_tag => App.config('associate_tags')[countryCode])

If this library is to support that, the usage would differ slightly to the API usage. But thanks for the pull!

**Comment by salza80** [comment]
OK. 

I just thought because you already do store the associate_tag so you don't have to pass it in on every request. 

Amazon::Ecs.configure do |options|
  options[:AWS_access_key_id] = '[your access key]'
  options[:AWS_secret_key] = '[you secret key]'
  options[:associate_tag] = '[your associate tag]'
end

But because i want to query multiple countries this is not helpful and I have to pass in both country code and associate tag on each request which i see more as configuration. 

Amazon::ECS.item_search('keyword', :associate_tag => App.config('associate_tags')[countryCode], :country_code =>countryCode)

**Comment by jugend** [comment]
Yeah I got the point, but must also remember not everyone needs the different associate tag, and we are reducing the clarity of what's the value of the options[:associate_tag], which now the default is a map, and could be overridden with a string. 

I just prefer clarity and consistency for this case. Sorry about it @salza80.

**Comment by jugend** [comment]
Note that there could also be a use case where one acts as a service provider that allows the users to tag their own associate ID, which means support for multiple tags for a single country. Thus I'm more keen to keep the implementation details outside of the API.

**Comment by salza80** [comment]
Yes, ok makes sense. Thanks for reviewing my pull.
Cheers.

**Pull request closed without merging**
